### ISSUE TITLE
What is the benifit of Paralus over kubelogin

### ISSUE THREAD

**Issue by Vad1mo** [paralus/paralus#101]
Paralus looks like a sophisticated piece of software, I am looking into ways on how to connect all our clusters with different providers to our OIDC IDP. I see all the features of Paralus, but many are IDP related, so what will I miss when using kubelogin with a powerful IDP

**Comment by akshay196** [comment]
@Vad1mo Thanks for showing interest. Paralus is build upon zero trust security framework  that does away with implicit trust and provides fine grained control over your applications and infrastructure.
Paralus comes with features like audit trails, Web kubectl and [more](https://www.paralus.io/docs/#features) out of box, along with CLI and GUI for managing clusters.

[This blog post](https://rafay.co/the-kubernetes-current/diy-access-management-using-dex-and-kubelogin/) explains more details about issues with DIY approach like kubelogin. Hope it helps.

**Comment by niravparikh05** [comment]
@Vad1mo hope the details shared by @akshay196 were helpful, please reach out to us on [slack](https://join.slack.com/t/paralus/shared_invite/zt-1a9x6y729-ySmAq~I3tjclEG7nDoXB0A) if you have any further clarifications / discussions around how paralus can act as a single controller and help scale when you have multiple clusters to manage.

Closing this isssue as it has been inactive for more than a month !
