### ISSUE TITLE
Namespace limitation input on roles

### ISSUE THREAD

**Issue by KenanHrnjic** [paralus/paralus#125]
### Expected vs actual behaviour

- When trying to assign namespace to a role I get error `No special char. allowed & length between 4-64 characters.` if namespace has any type of special character. This produces issues as namespaces can have `-` character in them
- Expected to be able to give read only namespace role to namespace `pr-test`

### Steps to reproduce the bug

1. Install Paralus
2. Go into Settings -> Groups -> Projects -> choose `Namespace Read Only` role -> in namespace part type in `pr-test`
3. You will get an error `No special char. allowed & length between 4-64 characters.`

### Are you using the latest version of the project?

- chart ztka-0.2.0
- app version v0.1.9

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

Environment is running on Google Cloud GKE
`kubectl version --outpout=yaml`
`clientVersion:
  buildDate: "2022-11-09T13:28:30Z"
  compiler: gc
  gitCommit: 872a965c6c6526caa949f0c6ac028ef7aff3fb78
  gitTreeState: clean
  gitVersion: v1.25.4
  goVersion: go1.19.3
  major: "1"
  minor: "25"
  platform: darwin/arm64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-10-26T09:25:23Z"
  compiler: gc
  gitCommit: 900b919b3b8275ecb9f70a489a318b5b08a4ab9c
  gitTreeState: clean
  gitVersion: v1.23.13-gke.900
  goVersion: go1.17.13b7
  major: "1"
  minor: "23"
  platform: linux/amd64`

`helm version`
`version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}`

WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1`

-

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

-

- [x] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [x] I'm using the latest version of the project.

**Comment by niravparikh05** [comment]
kubernetes namespace rules

character limit 1~63 
regex supported is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')
