### ISSUE TITLE
How do I log into the APIs?

### ISSUE THREAD

**Issue by estein9825** [paralus/paralus#127]
I tried using the `X-PARALUS-API-KEYID` against the auth/v3/userinfo request with the API Key I got from the JSON by downloading the cli config, but it failed authorization. I believe I have to authenticate somewhere, but I don't know the endpoint to do it.

Response failure is

```
{
    "code": 16,
    "message": "no or invalid credentials"
}
```

**Comment by estein9825** [comment]
For now I used the `X-API-KEYID` and `X-API-TOKEN` as mentioned here https://github.com/paralus/cli/blob/main/pkg/authprofile/key_profile.go#L32-L33. Had to base64 encode the md5sum of the secret as bytes though. Not ideal but a way to do it.

**Comment by niravparikh05** [comment]
@estein9825 you are right, below headers is required to get the api's working
X-API-KEYID -> api_key generated ( present in cli config )
X-API-TOKEN -> [base64 encoded value of md5 hash given the api_secret](https://go.dev/play/p/BjhIQi4E-Zx.go?download=true) ( present in cli config )

we will update the documentation / swagger accordingly
