### ISSUE TITLE
Update action version to latest 

### ISSUE THREAD

**Issue by OmAximani0** [paralus/paralus#130]
Since `action/checkout@v2` uses `Node 12.x.x` and it is [deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) I think we must use `action/checkout@v3`

https://github.com/paralus/paralus/blob/f9a079236246f8d352d2958ec7a5310cbf57cdd1/.github/workflows/go.yml#L17-L18

**Comment by akshay196** [comment]
@OmAximani0 Thanks for reporting. Let us know if you'd like to fix it, I can assign it to you.

**Comment by OmAximani0** [comment]
Yes I can create a PR for it
