### ISSUE TITLE
I inadvertently installed a relay agent in multiple clusters 

### ISSUE THREAD

**Issue by estein9825** [paralus/paralus#131]
We setup our paralus environment with the latest version using the standard operator and okta integration. Ever since doing so, we have gotten this noise in the logs. 

```
{"level":"error","ts":"2023-01-31T21:48:47.739Z","caller":"server/bootstrap.go:165","msg":"sql: no rows in result set","stacktrace":"github.com/paralus/paralus/server.(*bootstrapServer).RegisterBootstrapAgent\n\t/build/server/bootstrap.go:165\ngithub.com/paralus/paralus/proto/rpc/sentry._BootstrapService_RegisterBootstrapAgent_Handler.func1\n\t/build/proto/rpc/sentry/bootstrap_grpc.pb.go:330\ngithub.com/paralus/paralus/pkg/auth/v3.authContext.NewAuthUnaryInterceptor.func1\n\t/build/pkg/auth/v3/interceptor.go:27\ngithub.com/paralus/paralus/proto/rpc/sentry._BootstrapService_RegisterBootstrapAgent_Handler\n\t/build/proto/rpc/sentry/bootstrap_grpc.pb.go:332\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921"}
```

**Comment by estein9825** [comment]
Doing some more digging it looks like it occurs here: https://github.com/paralus/paralus/blob/f9a079236246f8d352d2958ec7a5310cbf57cdd1/server/bootstrap.go#L163, which is attempting to retrieving rows from the `sentry_bootstrap_agent_template` table. However, when I look in postgres, the table appears empty. At what point is that table supposed to be filled? I feel like we might have somehow skipped a step.

**Comment by estein9825** [comment]
Looks like it was because I inadvertently installed a relay agent in some non-existent servers during testing.

**Comment by techmaharaj** [comment]
Updating comments based on our discussion: Need to ensure that once a bootstrap is applied and a cluster is already imported to Paralus, we need to ensure that the same bootstrap cannot be used to bootstrap another cluster.
