### ISSUE TITLE
Get Relay Information Back for Cluster Import

### ISSUE THREAD

**Issue by estein9825** [paralus/paralus#140]
### Briefly describe the feature

When a cluster is imported for the first time, the relay information that is used by bootstrapping is put into the annotations. If you then make a cluster update to replace the annotations, the relay information disappears. The only way to retrieve it is then parse the bootstrap file for that information. 

### What problem does this feature solve? Please link any relevant documentation or Issues

Given the fact that the bootstrap info is the same across clusters save for the cluster ID and the relay information, it would be beneficial to get the relay information as an API return so a templated bootstrap could be used instead of the full bootstrap file.

### _(optional)_ What is your current workaround?

The current workaround is to retrieve the full bootstrap file and parse out the configmap data. I use this method to provide it as a return in my paralus provider

**Comment by niravparikh05** [comment]
Relay information is populated by paralus controller and should be read-only. 

Users should not be allowed to modify / remove the relay information during cluster update. 

Users can still add / remove other annotations as required.

**Comment by akshay196** [comment]
Cluster metadata.annotations is a place to store any non-identifying information of cluster for users. For example, user may store cloud provider information; it can used to identity the cloud provider used to provision this cluster.
However relay data is something Paralus uses internally and SHOULD NOT be placed in annotations or metadata.

Instead of converting "relay" in annotation read-only property which I believe is an extra work, we could move relay data to `cluster.Spec.ClusterData.ClusterStatus`. We are already storing "token" under ClusterStatus which cannot be updated by cluster UPDATE API.

@niravparikh05 WDYT?

**Comment by niravparikh05** [comment]
Storing relays information within cluster status does not seem right as it is definetely not related to status of a cluster, infact the same applies for token as well. However moving it within cluster.Spec.ClusterData makes sense, may be we can add a new field "relays". This definetely requires a lot more changes and regression, listing a few items that I can think of from top of my mind

1) Figure out database column to store this, currently it is stored as part of annotations. May be "extra" field can be utilized for this.
2) Changes to cluster create, update and get endpoints
3) Changes to cluster bootstrapping and download
4) Access impact to rctl and terraform
5) Access impact to existing users, it would definetely be a breaking change.

**Comment by akshay196** [comment]
@estein9825 As we decide on either of both options (readonly annotation or moving relay data under spec) where both have their ups and downs. If we support PATCH verb to cluster object that might solve the problem you're facing at updating cluster through terraform provider, is that right?

**Comment by estein9825** [comment]
Either is fine. Personally I’m processing the kubectl config file to get the values.

**Comment by niravparikh05** [comment]
thanks @estein9825 

After our internal discussion, we are continuing to use annotation as the place to store and process relay information.

Only change is that hereon, it will be of below format
paralus.io/relays

**Comment by niravparikh05** [comment]
As a separate enhancement, we may consider supporting PATCH for all the resources.
