### ISSUE TITLE
Add RBAC Access Granularity

### ISSUE THREAD

**Issue by estein9825** [paralus/paralus#162]
### Briefly describe the feature

Paralus control only offers an all/nothing when it comes to namespaces. Would be wonderful if we could also have more granular control like only viewing secrets or config maps or being able to edit everything except jobs.

### What problem does this feature solve? Please link any relevant documentation or Issues

Giving developers access to do things in their namespaces but not affect their secrets or exec into containers.

### _(optional)_ What is your current workaround?

No workaround at present. Am looking into possibly forking the code to offer this ability.

**Comment by estein9825** [comment]
Turns out the relay agent already has a guard that stops read and exec for any read roles: https://github.com/paralus/relay/blob/a7621d8c9f0387b143eaefc43caf972ebfbdb27b/pkg/tunnel/server.go#L767
https://github.com/paralus/relay/blob/e2ff5667153603898b25c17ab70ab6988f09c813/pkg/sessions/usersession.go#L98

So this is sufficient for our security needs. We can grant admin rights as needed to get beyond this. Still think having RBAC granularity would be nice, but at least it offers what we need out of the box. I'll leave it to you guys whether you want to close the ticket.

**Comment by niravparikh05** [comment]
thanks @estein9825 I am going to close this ticket. 

On a side note, we have another item on our roadmap to be able to provide kubernetes rbac level access to resources out of the box from paralus. We will be tracking that separately.
