### ISSUE TITLE
paralus main.go the number of  wg.add  is  not consistent

### ISSUE THREAD

**Issue by tyut22316** [paralus/paralus#202]
When I started reading main.go,I found that in the run function，the number of  wg.add  is  not consistent 
<img width="327" alt="image" src="https://user-images.githubusercontent.com/42953016/233317980-263d4478-d5f1-43f5-b9fe-73d9ac2dfd08.png">
I had to consult this version
[Update IdP and OIDC Provider](https://github.com/paralus/paralus/commit/7938f306682ba03ca8227ab8a5ccd4f8f2b936a6)
<img width="279" alt="image" src="https://user-images.githubusercontent.com/42953016/233318644-f826ce37-9673-4d92-99f7-f4a975e90751.png">

I think this number should be set to 6

**Comment by akshay196** [comment]
@tyut22316 Good catch! Would you like to raise PR to fix this?

**Comment by tyut22316** [comment]
> Would you like to raise PR to fix this

I'll be glad to do it
