### ISSUE TITLE
Add Trivy GitHub action for checking container images for vulnerability, SBOM and misconfigurations. 

### ISSUE THREAD

**Issue by Saim-Safdar** [paralus/paralus#210]
### Briefly describe the feature

- Need to continuously scan container images as upstream image(s) updates, patches, or upgrades, as new PR merge trigger a CI/CD pipeline using trivy GitHub actions. 

### What problem does this feature solve? Please link any relevant documentation or Issues

- Scan Docker container image for vulnerabilities [GitHub action for Trivy](https://github.com/aquasecurity/trivy-action)

### _(optional)_ What is your current workaround?

- Runs Trivy as GitHub action to scan your Docker container image for vulnerabilities

**Comment by akshay196** [comment]
Just a note: Docker Hub also provides image vulnerability scanning which is free for Sponsored Open source projects.
https://docs.docker.com/docker-hub/vulnerability-scanning/
https://docs.docker.com/docker-hub/dsos-program/#vulnerability-scanning

It looks like Trivy has more to offer than Docker vulnerability scanning.

**Comment by niravparikh05** [comment]
PRs merged for trivy

https://github.com/paralus/paralus/pull/219
https://github.com/paralus/relay/pull/62
https://github.com/paralus/prompt/pull/49
https://github.com/paralus/dashboard/pull/195

**Comment by niravparikh05** [comment]
Closing the issue as resolved.
