### ISSUE TITLE
Not able to view audit-logs/Web kubectl is throwing connection error/ Not able to download kubeconfig after upgrading from 0.2.2 to 0.2.4 chart version

### ISSUE THREAD

**Issue by divyanjali1** [paralus/paralus#215]
### Describe the issue you're facing

-I am facing the following issues
Not able to download kubeconfig
audit logs are not populating
web kubectl is throwing connection errors
[paralus.log](https://github.com/paralus/paralus/files/11433915/paralus.log)

Paralus log:
{"level":"error","ts":"2023-05-09T11:42:50.227Z","caller":"server/kubeconfig.go:62","msg":"error generating kubeconfig","error":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)","stacktrace":"github.com/paralus/paralus/server.(*kubeConfigServer).GetForUser\n\t/build/server/kubeconfig.go:62\ngithub.com/paralus/paralus/proto/rpc/sentry._KubeConfigService_GetForUser_Handler.func1\n\t/build/proto/rpc/sentry/kubeconfig_grpc.pb.go:247\ngithub.com/paralus/paralus/pkg/auth/v3.authContext.NewAuthUnaryInterceptor.func1\n\t/build/pkg/auth/v3/interceptor.go:129\ngithub.com/paralus/paralus/proto/rpc/sentry._KubeConfigService_GetForUser_Handler\n\t/build/proto/rpc/sentry/kubeconfig_grpc.pb.go:249\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921"}
{"level":"info","ts":"2023-05-09T11:49:46.275Z","caller":"reconcile/cluster_reconciler.go:197","msg":"unable to delete cluster","name":"linkerd-sm","error":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T11:49:46.292Z","caller":"reconcile/cluster_handler.go:184","msg":"unable to reconcile cluster","error":"unable to delete cluster: ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)","errorVerbose":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)\nunable to delete cluster\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).handleClusterDelete\n\t/build/pkg/reconcile/cluster_reconciler.go:198\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).Reconcile\n\t/build/pkg/reconcile/cluster_reconciler.go:48\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).handleClusterEvent\n\t/build/pkg/reconcile/cluster_handler.go:182\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).processNextCluster\n\t/build/pkg/reconcile/cluster_handler.go:102\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).runClusterWorker\n\t/build/pkg/reconcile/cluster_handler.go:108\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","event":"ev"}
{"level":"info","ts":"2023-05-09T11:49:46.293Z","caller":"reconcile/cluster_reconciler.go:197","msg":"unable to delete cluster","name":"linkerd-sm","error":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T11:49:46.318Z","caller":"reconcile/cluster_handler.go:184","msg":"unable to reconcile cluster","error":"unable to delete cluster: ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)","errorVerbose":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)\nunable to delete cluster\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).handleClusterDelete\n\t/build/pkg/reconcile/cluster_reconciler.go:198\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).Reconcile\n\t/build/pkg/reconcile/cluster_reconciler.go:48\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).handleClusterEvent\n\t/build/pkg/reconcile/cluster_handler.go:182\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).processNextCluster\n\t/build/pkg/reconcile/cluster_handler.go:102\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).runClusterWorker\n\t/build/pkg/reconcile/cluster_handler.go:108\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","event":"ev"}
{"level":"info","ts":"2023-05-09T11:49:59.027Z","caller":"reconcile/cluster_reconciler.go:197","msg":"unable to delete cluster","name":"linkerd-sm","error":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T11:49:59.038Z","caller":"reconcile/cluster_reconciler.go:197","msg":"unable to delete cluster","name":"linkerd-sm","error":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T11:49:59.044Z","caller":"reconcile/cluster_handler.go:184","msg":"unable to reconcile cluster","error":"unable to delete cluster: ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)","errorVerbose":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)\nunable to delete cluster\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).handleClusterDelete\n\t/build/pkg/reconcile/cluster_reconciler.go:198\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).Reconcile\n\t/build/pkg/reconcile/cluster_reconciler.go:48\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).handleClusterEvent\n\t/build/pkg/reconcile/cluster_handler.go:182\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).processNextCluster\n\t/build/pkg/reconcile/cluster_handler.go:102\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).runClusterWorker\n\t/build/pkg/reconcile/cluster_handler.go:108\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","event":"ev"}
{"level":"info","ts":"2023-05-09T11:49:59.060Z","caller":"reconcile/cluster_handler.go:184","msg":"unable to reconcile cluster","error":"unable to delete cluster: ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)","errorVerbose":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)\nunable to delete cluster\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).handleClusterDelete\n\t/build/pkg/reconcile/cluster_reconciler.go:198\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).Reconcile\n\t/build/pkg/reconcile/cluster_reconciler.go:48\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).handleClusterEvent\n\t/build/pkg/reconcile/cluster_handler.go:182\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).processNextCluster\n\t/build/pkg/reconcile/cluster_handler.go:102\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).runClusterWorker\n\t/build/pkg/reconcile/cluster_handler.go:108\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","event":"ev"}
{"level":"info","ts":"2023-05-09T11:51:26.943Z","caller":"reconcile/cluster_reconciler.go:197","msg":"unable to delete cluster","name":"linkerd-sm","error":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T11:51:26.960Z","caller":"reconcile/cluster_handler.go:184","msg":"unable to reconcile cluster","error":"unable to delete cluster: ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)","errorVerbose":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)\nunable to delete cluster\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).handleClusterDelete\n\t/build/pkg/reconcile/cluster_reconciler.go:198\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).Reconcile\n\t/build/pkg/reconcile/cluster_reconciler.go:48\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).handleClusterEvent\n\t/build/pkg/reconcile/cluster_handler.go:182\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).processNextCluster\n\t/build/pkg/reconcile/cluster_handler.go:102\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).runClusterWorker\n\t/build/pkg/reconcile/cluster_handler.go:108\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","event":"ev"}
{"level":"error","ts":"2023-05-09T11:51:38.990Z","caller":"server/kubeconfig.go:62","msg":"error generating kubeconfig","error":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)","stacktrace":"github.com/paralus/paralus/server.(*kubeConfigServer).GetForUser\n\t/build/server/kubeconfig.go:62\ngithub.com/paralus/paralus/proto/rpc/sentry._KubeConfigService_GetForUser_Handler.func1\n\t/build/proto/rpc/sentry/kubeconfig_grpc.pb.go:247\ngithub.com/paralus/paralus/pkg/auth/v3.authContext.NewAuthUnaryInterceptor.func1\n\t/build/pkg/auth/v3/interceptor.go:129\ngithub.com/paralus/paralus/proto/rpc/sentry._KubeConfigService_GetForUser_Handler\n\t/build/proto/rpc/sentry/kubeconfig_grpc.pb.go:249\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921"}
{"level":"error","ts":"2023-05-09T11:51:47.453Z","caller":"server/kubeconfig.go:62","msg":"error generating kubeconfig","error":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)","stacktrace":"github.com/paralus/paralus/server.(*kubeConfigServer).GetForUser\n\t/build/server/kubeconfig.go:62\ngithub.com/paralus/paralus/proto/rpc/sentry._KubeConfigService_GetForUser_Handler.func1\n\t/build/proto/rpc/sentry/kubeconfig_grpc.pb.go:247\ngithub.com/paralus/paralus/pkg/auth/v3.authContext.NewAuthUnaryInterceptor.func1\n\t/build/pkg/auth/v3/interceptor.go:129\ngithub.com/paralus/paralus/proto/rpc/sentry._KubeConfigService_GetForUser_Handler\n\t/build/proto/rpc/sentry/kubeconfig_grpc.pb.go:249\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921"}
{"level":"info","ts":"2023-05-09T11:57:39.190Z","caller":"reconcile/cluster_reconciler.go:197","msg":"unable to delete cluster","name":"linkerd-sm","error":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T11:57:39.207Z","caller":"reconcile/cluster_reconciler.go:197","msg":"unable to delete cluster","name":"linkerd-sm","error":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T11:57:39.208Z","caller":"reconcile/cluster_handler.go:184","msg":"unable to reconcile cluster","error":"unable to delete cluster: ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)","errorVerbose":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)\nunable to delete cluster\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).handleClusterDelete\n\t/build/pkg/reconcile/cluster_reconciler.go:198\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).Reconcile\n\t/build/pkg/reconcile/cluster_reconciler.go:48\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).handleClusterEvent\n\t/build/pkg/reconcile/cluster_handler.go:182\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).processNextCluster\n\t/build/pkg/reconcile/cluster_handler.go:102\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).runClusterWorker\n\t/build/pkg/reconcile/cluster_handler.go:108\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","event":"ev"}
{"level":"info","ts":"2023-05-09T11:57:39.230Z","caller":"reconcile/cluster_handler.go:184","msg":"unable to reconcile cluster","error":"unable to delete cluster: ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)","errorVerbose":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)\nunable to delete cluster\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).handleClusterDelete\n\t/build/pkg/reconcile/cluster_reconciler.go:198\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).Reconcile\n\t/build/pkg/reconcile/cluster_reconciler.go:48\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).handleClusterEvent\n\t/build/pkg/reconcile/cluster_handler.go:182\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).processNextCluster\n\t/build/pkg/reconcile/cluster_handler.go:102\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).runClusterWorker\n\t/build/pkg/reconcile/cluster_handler.go:108\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","event":"ev"}
{"level":"info","ts":"2023-05-09T11:57:44.135Z","caller":"reconcile/cluster_reconciler.go:197","msg":"unable to delete cluster","name":"caas-np01-slvr1-121","error":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T11:57:44.136Z","caller":"reconcile/cluster_reconciler.go:197","msg":"unable to delete cluster","name":"caas-np01-slvr1-121","error":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T11:57:44.155Z","caller":"reconcile/cluster_handler.go:184","msg":"unable to reconcile cluster","error":"unable to delete cluster: ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)","errorVerbose":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)\nunable to delete cluster\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).handleClusterDelete\n\t/build/pkg/reconcile/cluster_reconciler.go:198\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).Reconcile\n\t/build/pkg/reconcile/cluster_reconciler.go:48\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).handleClusterEvent\n\t/build/pkg/reconcile/cluster_handler.go:182\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).processNextCluster\n\t/build/pkg/reconcile/cluster_handler.go:102\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).runClusterWorker\n\t/build/pkg/reconcile/cluster_handler.go:108\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","event":"ev"}
{"level":"info","ts":"2023-05-09T11:57:44.176Z","caller":"reconcile/cluster_handler.go:184","msg":"unable to reconcile cluster","error":"unable to delete cluster: ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)","errorVerbose":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)\nunable to delete cluster\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).handleClusterDelete\n\t/build/pkg/reconcile/cluster_reconciler.go:198\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterReconciler).Reconcile\n\t/build/pkg/reconcile/cluster_reconciler.go:48\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).handleClusterEvent\n\t/build/pkg/reconcile/cluster_handler.go:182\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).processNextCluster\n\t/build/pkg/reconcile/cluster_handler.go:102\ngithub.com/paralus/paralus/pkg/reconcile.(*clusterEventHandler).runClusterWorker\n\t/build/pkg/reconcile/cluster_handler.go:108\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.4/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","event":"ev"}
{"level":"error","ts":"2023-05-09T11:57:47.910Z","caller":"server/kubeconfig.go:62","msg":"error generating kubeconfig","error":"ERROR: column ks.sa_validity_seconds does not exist (SQLSTATE=42703)","stacktrace":"github.com/paralus/paralus/server.(*kubeConfigServer).GetForUser\n\t/build/server/kubeconfig.go:62\ngithub.com/paralus/paralus/proto/rpc/sentry._KubeConfigService_GetForUser_Handler.func1\n\t/build/proto/rpc/sentry/kubeconfig_grpc.pb.go:247\ngithub.com/paralus/paralus/pkg/auth/v3.authContext.NewAuthUnaryInterceptor.func1\n\t/build/pkg/auth/v3/interceptor.go:129\ngithub.com/paralus/paralus/proto/rpc/sentry._KubeConfigService_GetForUser_Handler\n\t/build/proto/rpc/sentry/kubeconfig_grpc.pb.go:249\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:921"}

Prompt logs :
{"level":"info","ts":"2023-05-09T12:56:17.151Z","caller":"debug/handler.go:130","msg":"unable to get kubeconfig using GetForClusterWebSession","error":"rpc error: code = Unknown desc = ERROR: column [ks.sa](http://ks.sa/)_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T12:56:17.151Z","caller":"debug/handler.go:186","msg":"unable to get kube config","error":"rpc error: code = Unknown desc = ERROR: column [ks.sa](http://ks.sa/)_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T13:21:59.852Z","caller":"debug/handler.go:130","msg":"unable to get kubeconfig using GetForClusterWebSession","error":"rpc error: code = Unknown desc = ERROR: column [ks.sa](http://ks.sa/)_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T13:21:59.852Z","caller":"debug/handler.go:186","msg":"unable to get kube config","error":"rpc error: code = Unknown desc = ERROR: column [ks.sa](http://ks.sa/)_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T13:22:08.620Z","caller":"debug/handler.go:130","msg":"unable to get kubeconfig using GetForClusterWebSession","error":"rpc error: code = Unknown desc = ERROR: column [ks.sa](http://ks.sa/)_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T13:22:08.620Z","caller":"debug/handler.go:186","msg":"unable to get kube config","error":"rpc error: code = Unknown desc = ERROR: column [ks.sa](http://ks.sa/)_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T13:22:22.824Z","caller":"debug/handler.go:130","msg":"unable to get kubeconfig using GetForClusterWebSession","error":"rpc error: code = Unknown desc = ERROR: column [ks.sa](http://ks.sa/)_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T13:22:22.824Z","caller":"debug/handler.go:186","msg":"unable to get kube config","error":"rpc error: code = Unknown desc = ERROR: column [ks.sa](http://ks.sa/)_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T14:07:54.878Z","caller":"debug/handler.go:130","msg":"unable to get kubeconfig using GetForClusterWebSession","error":"rpc error: code = Unknown desc = ERROR: column [ks.sa](http://ks.sa/)_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T14:07:54.878Z","caller":"debug/handler.go:186","msg":"unable to get kube config","error":"rpc error: code = Unknown desc = ERROR: column [ks.sa](http://ks.sa/)_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T14:31:12.100Z","caller":"debug/handler.go:130","msg":"unable to get kubeconfig using GetForClusterWebSession","error":"rpc error: code = Unknown desc = ERROR: column [ks.sa](http://ks.sa/)_validity_seconds does not exist (SQLSTATE=42703)"}
{"level":"info","ts":"2023-05-09T14:31:12.100Z","caller":"debug/handler.go:186","msg":"unable to get kube config","error":"rpc error: code = Unknown desc = ERROR: column [ks.sa](http://ks.sa/)_validity_seconds does not exist (SQLSTATE=42703)"}

**Comment by divyanjali1** [comment]
I have ran this command , @niravparikh05  has provided. I am able to access web kubectl and kubeconfig
How can we upgrade relay-agent on the cluster after upgrading the relay-server

**Comment by akshay196** [comment]
> How can we upgrade relay-agent on the cluster after upgrading the relay-server

@divyanjali1 You can update relay-agent on the clusters by updating the relay-agent image. This can be done using following command:
```
kubectl -n paralus-system set image deployment relay-agent relay-agent=paralusio/relay:v0.1.4
```

We are discussing [here](https://github.com/paralus/paralus/issues/217) about adding new feature that automatically update agent on imported cluster. Stay tune.
