### ISSUE TITLE
PROJECT_ADMIN/CLUSTER_ADMIN/CLUSTER_ADMIN_READONLY roles not able to view audit logs

### ISSUE THREAD

**Issue by divyanjali1** [paralus/paralus#225]
### Expected vs actual behavior
User/Groups with the following roles should be able to view audit-logs for that paticular project and cluster
PROJECT_ADMIN/CLUSTER_ADMIN/CLUSTER_ADMIN_READONLY 
-

### Steps to reproduce the bug

1. Create/Add new User/Group in Paralus Dashbaord
2. Assign one of the above mentioned roles to User/Group
3. Check audit-logs section in dashboard

### Are you using the latest version of the project? Yes

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

- NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
paralus paralus         5               2023-05-22 06:09:11.808502642 +0000 UTC deployed        ztka-0.2.4      v0.2.3

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!
>helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

kubectl version --output=yaml
clientVersion:
  buildDate: "2021-01-13T13:23:52Z"
  compiler: gc
  gitCommit: 1dd5338295409edcfff11505e7bb246f0d325d15
  gitTreeState: clean
  gitVersion: v1.19.7
  goVersion: go1.15.5
  major: "1"
  minor: "19"
  platform: windows/amd64
serverVersion:
  buildDate: "2023-04-15T00:32:27Z"
  compiler: gc
  gitCommit: cd5c12c51b0899612375453f7a7c2e7b6563f5e9
  gitTreeState: clean
  gitVersion: v1.23.17-eks-0a21954
  goVersion: go1.19.6
  major: "1"
  minor: 23+
  platform: linux/amd64
==========================
- Paralus is installed on EKS cluster.

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

-

- [ ] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [ ] I'm using the latest version of the project.

**Comment by niravparikh05** [comment]
This has a bunch of things to be done including cleanup, listing down as tasks to capture the progress

- [ ] remove not in use permissions `audit.read` and `project.audit.read` and update corresponding roles accordingly
- [ ] update permissions `org.relayAudit.read` and `project.relayAudit.read` to  use `/event/v1/audit/relay` and `/event/v1/{metadata.urlScope=project/*}/audit/relay` 
- [ ] remove redundant endpoints `/event/v1/relayaudit` and `/event/v1/project/:project_id/relayaudit`
- [ ] changes to support viewing auditlogs for project admin / read only users
- [ ] changes to support viewing cluster auditlogs for cluster admin / read only users
- [ ] Dashboard changes to support viewing auditlogs for project admin / read only users
- [ ] Dashboard changes to support viewing cluster auditlogs for cluster admin / read only users
