### ISSUE TITLE
DB Migration Fails If Postgres < 14 is used with Paralus Version >= 0.2.2

### ISSUE THREAD

**Issue by estein9825** [paralus/paralus#234]
### Expected vs actual behavior

When creating triggers, migration specifies `CREATE OR REPLACE` which is not supported until PostgreSQL 14. 

e.g. https://github.com/paralus/paralus/blob/v0.2.2/persistence/migrations/admindb/000030_pg_oidc_provider_triggers.up.sql

The result is the following error:

`error: Dirty database version 30. Fix and force version.`

Running it locally will yield this error instead:
```
error: migration failed: syntax error at or near "TRIGGER" (column 19) in line 8: CREATE OR REPLACE FUNCTION providers_after_change_trigger() RETURNS TRIGGER AS $$
  BEGIN
    PERFORM pg_notify('provider:changed', '');
    RETURN NULL;
  END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER providers_updated
  AFTER UPDATE ON authsrv_oidc_provider
  FOR EACH ROW EXECUTE PROCEDURE providers_after_change_trigger();

CREATE OR REPLACE TRIGGER providers_inserted
  AFTER INSERT ON authsrv_oidc_provider
  FOR EACH ROW EXECUTE PROCEDURE providers_after_change_trigger();

CREATE OR REPLACE TRIGGER providers_deleted
  AFTER DELETE ON authsrv_oidc_provider
  FOR EACH ROW EXECUTE PROCEDURE providers_after_change_trigger();
 (details: pq: syntax error at or near "TRIGGER")
```
Therefore, PostgreSQL 14 is a requirement for deployments now. We need to make a note in the documentation for those who deploy postgresql separately. Or add separate scripts that will do a DROP IF EXISTS and CREATE after.

### Steps to reproduce the bug

1. Install postgresql 11
2. Startup paralus and have it go through the init containers.
3. Log will fail with `error: Dirty database version 30. Fix and force version.`

### Are you using the latest version of the project?

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

paralus 0.2.2

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

-

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

This is a breaking change. The SQL script for 0.2.1 is different from 0.2.2

0.2.1: https://github.com/paralus/paralus/blob/v0.2.1/persistence/migrations/admindb/000030_pg_oidc_provider_triggers.up.sql
0.2.2: https://github.com/paralus/paralus/blob/v0.2.2/persistence/migrations/admindb/000030_pg_oidc_provider_triggers.up.sql

- [X ] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [X ] I'm using the latest version of the project.

**Comment by akshay196** [comment]
@estein9825 Thanks for reporting. I think we recently moved to CREATE OR REPLACE statements to avoid errors in rerunning migrations, but this goes unnoticed. 

> add separate scripts that will do a DROP IF EXISTS and CREATE after.

This sound good approach to me. We can replace the `CREATE OR REPLACE` triggers with `DROP IF EXISTS` + `CREATE` statements.

**Comment by hitesh-infracloud** [comment]
Hi @akshay196 could you please assign this to me?

**Comment by HiteshRepo** [comment]
Hi @akshay196 please assign this to me.
