### ISSUE TITLE
Comma separated Okta groups are considered as Single group by Paralus

### ISSUE THREAD

**Issue by divyanjali1** [paralus/paralus#244]
### Expected vs actual behavior
Comma separated Okta groups should be considered as different group each by Paralus and if granted access to one group in which the IDP users is part of, user should be able to access the projects based on permissions given
-
All the comma separated groups populated in paralus are cosidered as single group and user is not able to access projects even if group is granted access to project.
### Steps to reproduce the bug

1. Integrate Okta with Paralus.
2. Enable group mapping to paralus from okta
3. Login to paralus with user ID who is part of multiple groups from Okta end.

### Are you using the latest version of the project?
v0.2.3
You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.
v0.2.3
-

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!
AWS EKS.
-
Using custom jsonnet.
local claims = std.extVar('claims');

local fName = if "name" in claims && claims.name!=null && std.length(std.findSubstr(" ", claims.name)) > 0 then std.splitLimit(claims.name, " ", 1)[0] else "Paralus";
local lName = if "name" in claims && claims.name!=null && std.length(std.findSubstr(" ", claims.name)) > 0 then std.splitLimit(claims.name, " ", 1)[1] else "User";

{
  identity: {
    traits: {
      email: claims.email,
      first_name: fName,
      last_name: lName,
      [if "groups" in claims.raw_claims then "idp_groups" else null]: [ claims.raw_claims.groups ],
    },
  },
### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

-

- [ ] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [ ] I'm using the latest version of the project.

**Comment by akshay196** [comment]
@divyanjali1 Can you try this following line instead
```
[if "groups" in claims.raw_claims then "idp_groups" else null]: std.split(claims.raw_claims.groups, ','),
```
[By default](https://github.com/paralus/paralus/blob/b4d64ef565c089da75c6e358ce6943d54aa91b93/_kratos/oidc-mappers/okta.jsonnet#L15) we would expect OIDC groups as a list of items instead of string. But one can change Jsonnet script for user data mapping as per their OIDC setup and need.

Discussed in [Slack thread here](https://paralus.slack.com/archives/C03JEA9EFUH/p1692280775253019?thread_ts=1684745864.404439&cid=C03JEA9EFUH).

**Comment by divyanjali1** [comment]
Thank you Akshay , changing okta jsonnet resolved the issue.

**Comment by akshay196** [comment]
Glad it helped. Closing this issue, feel free to reopen if you've further queries.
