### ISSUE TITLE
Cluster status - heartbeat: Ability to regularly check in on the target cluster status

### ISSUE THREAD

**Issue by niravparikh05** [paralus/paralus#245]
### Briefly describe the feature

- Cluster status - heartbeat: Ability to regularly check in on the target cluster status
- Display current status near Cluster in dashboard

### What problem does this feature solve? Please link any relevant documentation or Issues

- Currently, if a cluster gets disconnected. There is no way user will know about it right now.

### _(optional)_ What is your current workaround?

- web kubectl connectivity fails, need to manually check relay-agent logs.

**Comment by karthikmurali60** [comment]
Hi @niravparikh05 !!!
I would like to work on this issue. It would be of great help if you could provide some information as to how the heartbeat can be implemented ?

**Comment by niravparikh05** [comment]
thanks @karthikmurali60 for your Interest ! We have curated a list of TODO's for folks contributing to Paralus, this helps to avoid lot of back and forth and saves time.

- [ ] Assign this issue to yourself
- [ ] Document your initial analysis and implemention approach ( details like what changes are required for this feature )
- [ ] Submit the above document for review
- [ ] Once approach is finalized, create a pr with your code changes for review
- [ ] Maintainer review and approval
- [ ] Code Merge
- [ ] Add a badge, make a statement, share proudly of your first contribution to Paralus

**Comment by niravparikh05** [comment]
hey @karthikmurali60 just following up if you got a chance to work on this.
