### ISSUE TITLE
Problem with golang library in Relay server

### ISSUE THREAD

**Issue by wgerasimov** [paralus/paralus#266]
### Expected vs actual behavior

After some time the external cluster which been connected to the Paralus server ceases to be accessible from the web console. 
Images here

![8474-f239-53ea-6aeb](https://github.com/paralus/paralus/assets/55928738/2b8784db-2bf3-47b9-b51a-2a86efd4e9ff)

Button "reconnect" doesn't fix this problem

### Steps to reproduce the bug

1. Install paralus server using by helm chart
2. Using the instructions, connect another k8s cluster
3. After 6-12 hours, you can see "Connection Error" in the web console

### Are you using the latest version of the project?

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

- Paralus was installed using ArgoCD. Helm chart version ztka:0.2.6

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

- Red Hat Enterprise Linux release 8.8 (Ootpa)
- clientVersion:
  buildDate: "2023-07-19T12:20:54Z"
  compiler: gc
  gitCommit: fa3d7990104d7c1f16943a67f11b154b71f6a132
  gitTreeState: clean
  gitVersion: v1.27.4
  goVersion: go1.20.6
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-07-19T12:14:49Z"
  compiler: gc
  gitCommit: fa3d7990104d7c1f16943a67f11b154b71f6a132
  gitTreeState: clean
  gitVersion: v1.27.4
  goVersion: go1.20.6
  major: "1"
  minor: "27"
  platform: linux/amd64

- Helm: version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

I was able to solve this problem using values.yml with parameter images.reley.tag="v0.1.4". In this Reley Images using golang library golang.org/x/net v0.0.0-20210825183410-e898025ed96a thich resolve problem with number of open sokcet in virtual machine. For example, now i see:

[@~]# kubectl -n paralus exec relay-server-5b459f7-85vkd -c relay-server -it -- lsof | grep socket | wc -l
63

When I used the latest version (images.reley.tag="v0.1.6"), there were 2.5K+ open sockets.

A similar problem was described and solved earlier, but with the chart version ztka:0.2.{5,6} it happened again.

- [x] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [x] I'm using the latest version of the project.

**Comment by niravparikh05** [comment]
Using the latest versions also seemed to work fine however looks like this issue occurs with latest versions too, refer: [read unix @->/tmp/relay-unix periodic error](https://github.com/paralus/relay/issues/43)

As of now, pinning the version of golang.org/x/net library would solve it

replace (
golang.org/x/net => golang.org/x/net v0.0.0-20210825183410-e898025ed96a
)

**Comment by akshay196** [comment]
@wgerasimov Hey,
Just checking if you get a chance to try above modification suggested by @niravparikh05

**Comment by niravparikh05** [comment]
We have been monitoring this issue with the latest version and do not encounter any issues with connectivity. 

Note: there's not been a lot of users / activity over the past month though

**Comment by niravparikh05** [comment]
Update: Closing this since we have not observed this issue during recent times. If you are still facing this, please upgrade your paralus deployments and verify again and if it still persists then feel free to open a new issue with specific details so as to help us debug further.
