### ISSUE TITLE
Need Architecture Diagram for the Paralus Setup

### ISSUE THREAD

**Issue by praddy26** [paralus/paralus#27]
Need an architecture diagram 
- Depicting the various components involved in the setup
- Interactions happening between the components
- Different touchpoints
- Protocols being used

Why is this needed?
- Helps new developers to get started with confidence
- Helps security team in evaluating the tool from security perspective
- SRE/DevOps folks gets the picture of the whole setup

**Comment by techmaharaj** [comment]
Fixed as part of the [latest update](https://github.com/paralus/website/pull/42), hence closing.
