### ISSUE TITLE
unable to access paralus dashboard

### ISSUE THREAD

**Issue by Sreeja-zelarsoft** [paralus/paralus#273]
I attempted to install Paralus in k3s cluster using the information provided on offical document and while the deployment was successful, I am unable to access the dashboard as it does not receive an external IP address for Paralus.

**Comment by niravparikh05** [comment]
hello @Sreeja-zelarsoft, can you provide more information like which ingress did you use ? Looks like k3s comes with [traefik ingress by default](https://docs.k3s.io/networking)

Can you disable traefik while installing k3s and try again, you should be able to see external-ip with below command ( using default ingress - contour )
`kubectl get svc myrelease-contour-envoy -n paralus`

Once you have that handy, setup DNS settings by following [these steps here](https://www.paralus.io/blog/paralus-quickstart-gke#configuring-dns-settings) ( these steps are identical for any cluster type )

**Comment by Sreeja-zelarsoft** [comment]
We followed the official documentation steps to install Paralus on an EKS cluster. Although Paralus was successfully installed, we encountered issues accessing the Paralus dashboard. Our EKS cluster utilizes the default load balancer, and we are exploring the possibility of accessing the dashboard without DNS configuration.

**Comment by Sreeja-zelarsoft** [comment]
Resolved thank you..

**Comment by akshay196** [comment]
Closing.. Reopen if further help needed.
