### ISSUE TITLE
Unable to download cli config for non-admin users

### ISSUE THREAD

**Issue by niravparikh05** [paralus/paralus#274]
### Expected vs actual behavior

- User should be able to download cli config

### Steps to reproduce the bug

1. Create a user ( mostly observed for non-admin users )
2. Login to dashboard as that user
3. Click on download cli config from tools system menu

### Are you using the latest version of the project?

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

-

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

-

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

-

- [ ] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [ ] I'm using the latest version of the project.

**Comment by Bharadwajshivam28** [comment]
I can take on this issue but I need some more details and steps to get started

**Comment by niravparikh05** [comment]
@Bharadwajshivam28 Issue is with missing permissions across non-admin roles, we should create a new permission file with below and add this to all non-admin roles in roles.json under ztka. Will you be able to take care of it ?

`{
    "name": "cli.config.read",
    "resource_urls": [
      {
        "url": "/cli/config",
        "methods": [
          "GET"
        ]
      }
    ],
    "base_url": "/auth/v3",
    "description": "CLI Configuration",
    "authenticated": true,
    "scope": "PROJECT"
  }`
