### ISSUE TITLE
Namespaces should not be created

### ISSUE THREAD

**Issue by niravparikh05** [paralus/paralus#37]
### Expected vs actual behavior

- Expectation is that a namespace provided while associating a namespace role should be available in target cluster and Paralus should not create a namespace if it already exists.
- Current behaviour creates a namespace in target cluster if not already present.

### Steps to reproduce the bug

1. Assign a namespace related role to a user and provide a namespace name that does not exist in target cluster
2. verify kubectl get ns in target cluster - namespace should not exist
3. Perform web kubectl from Paralus and you can now see that namespace is created.

### Are you using the latest version of the project?

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

- Yes, v0.1.0

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

- Impacts all environments

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

- Code to check if namespace exists and create if not needs to be removed from relay and paralus sentry package.

- [x] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [x] I'm using the latest version of the project.

**Comment by meain** [comment]
I had create a ticket for this at [paralus/relay#28](https://github.com/paralus/relay/issues/28) as well :D. We could probably clone one of them.

**Comment by niravparikh05** [comment]
Closing this here, please track above mentioned issue for further updates.
