### ISSUE TITLE
Interactive installation for Paralus

### ISSUE THREAD

**Issue by techmaharaj** [paralus/paralus#38]
### Briefly describe the feature
Currently the user has to provide/create a `yaml` file during installation with custom values based on their requirement. Paralus will be deployed with those values. Further, there are different yaml files for different environments - _EKS, AKS, GCP etc._ so the user needs to supply the correct yaml file to correctly configure Paralus.

The idea is to have an interactive installation of Paralus where the user is asked for inputs for the configurable values and doesn't have to deal with yaml files at all.

For Eg. ask the following questions during installation:
- Are you deploying Paralus for testing or production?
- Provide a domain name to use for Paralus _(if left blank, the default value will be used)_
- Provide the admin user email id _(if left blank, the default value will be used)_
- Provide the organization name _(if left blank, the default value will be used)_

### What problem does this feature solve? Please link any relevant documentation or Issues

Improves the user experience and makes it less complex. Currently the user needs to supply a specific yaml file or create a different one to install Paralus. With this interactive installation, user no more deals with updating values in yaml file which now will be taken care of by Paralus.

**Comment by niravparikh05** [comment]
After much deliberation during our community call ( dated 26th March, ref: [minutes](https://docs.google.com/document/d/1yX2Y9ZJa0g4RLYG8rGp55pFTiEfHo1LpiF5p3ut3P1s/edit?usp=sharing) ), this surely will give users a different installation experience however considering the ROI on this and given there are other features in our backlog which we would want to focus on, we are closing this issue.

In case you are really interested in this feature, please reopen and come up with a design document which we will discuss during our community call with all stakeholders and proceed further.
