### ISSUE TITLE
Fix lint issues from buf

### ISSUE THREAD

**Issue by meain** [paralus/paralus#40]
### Expected vs actual behavior

Expected: pass `buf lint`

### Steps to reproduce the bug

1. Run `buf lint`

- [x] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [x] I'm using the latest version of the project.

Log: [buf-lint.log](https://github.com/paralus/paralus/files/9101602/buf-lint.log)

_Most of them are naming convention details_

**Comment by niravparikh05** [comment]
Fixed below categories of lint issues and the rest are exempted ( will be prioritized for future releases ).

- FILE_LAYOUT
- SERVICE_SUFFIX
- MESSAGE_PASCAL_CASE
- RPC_PASCAL_CASE
- PACKAGE_SAME_GO_PACKAGE
- UNUSED
