### ISSUE TITLE
New public ( No auth ) partner, organization api to fetch very basic infrormation

### ISSUE THREAD

**Issue by niravparikh05** [paralus/paralus#49]
### Briefly describe the feature

- Add new organization and partner basic information api which will be non-restricted and public
- Only organization, partner id and name information will be fetched
- Will be used in dashboard to load before user login
- Impact to CLI to be checked
- Remove the existing mandatory permissions validation for organization / partner
- Skip only kubectl related permissions from authz.

### What problem does this feature solve? Please link any relevant documentation or Issues

- It removes the dependency for all custom roles to have organization, partner read only permissions. Thus enabling creating custom roles with just hand-picked api permissions depending on the use case.

### _(optional)_ What is your current workaround?

- Currently, while creating custom roles organization, partner read permissions are made mandatory so that users / systems can use those custom roles

**Comment by akshay196** [comment]
@niravparikh05 Exposing an API publicly without authentication will raise security concerns. Let's reassess this ticket since it is been a while you created it.

**Comment by niravparikh05** [comment]
Deprioritizing and closing this.
