### ISSUE TITLE
Move to using bun's builtin `soft_delete` mechanism

### ISSUE THREAD

**Issue by meain** [paralus/paralus#6]
ref: https://bun.uptrace.dev/guide/soft-deletes.html#introduction

**Comment by meain** [comment]
This will require some kind of migration path.

**Comment by niravparikh05** [comment]
After much deliberation during our community call ( dated 26th March, ref: [minutes](https://docs.google.com/document/d/1yX2Y9ZJa0g4RLYG8rGp55pFTiEfHo1LpiF5p3ut3P1s/edit?usp=sharing) ), this comes as a tech debt item which does not really add much value to users, it's decided to use bun's soft_delete mechanism in upcoming features however we do not plan to refactor the existing code in the near future.
