### ISSUE TITLE
cannot access Paralus Dashboard in M1 Mac

### ISSUE THREAD

**Issue by rustiever** [paralus/paralus#68]
### Expected vs actual behavior

- after paralus installation we should be able access `http://console.paralus.local`. But its not loading. Im using M1 Mac Air system.

### Steps to reproduce the bug

1. Follow this [blog](https://www.paralus.io/blog/kind-quickstart) on M1 Mac.
2. once installation is completed try to access `http://console.paralus.local`

### Are you using the latest version of the project?

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

APP VERSION
v0.1.3

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

- `kubectl version --output=yaml`

> clientVersion:
  buildDate: "2021-12-16T08:38:33Z"
  compiler: gc
  gitCommit: 5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e
  gitTreeState: clean
  gitVersion: v1.22.5
  goVersion: go1.16.12
  major: "1"
  minor: "22"
  platform: darwin/arm64
serverVersion:
  buildDate: "2022-05-19T15:42:59Z"
  compiler: gc
  gitCommit: 4ce5a8954017644c5420bae81d72b09b735c21f0
  gitTreeState: clean
  gitVersion: v1.24.0
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: linux/arm64

WARNING: version difference between client (1.22) and server (1.24) exceeds the supported minor version skew of +/-1

- `helm version`
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

-

- [x] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [x] I'm using the latest version of the project.

**Comment by sandeep540** [comment]
Docker on Mac does not let you connect to container internal IP unlike Linux, to access the internal (which is mapped to console.paralus.local), it needs a tunnel 

This tool https://github.com/chipmk/docker-mac-net-connect, once installed and run successfully as sudo will let you access internal IP

Tested the same in Mac M1 and was able to connect @ http://console.paralus.local 


![Screenshot 2022-09-19 at 4 20 25 PM](https://user-images.githubusercontent.com/741952/191001847-5b5bdb6c-c27d-4bbc-a776-c20bd1406795.png)

**Comment by techmaharaj** [comment]
This is fixed via https://github.com/paralus/website/pull/52, closing the issue.
