### ISSUE TITLE
Ability to set auto generated password during installation and force reset during first login

### ISSUE THREAD

**Issue by niravparikh05** [paralus/paralus#92]
### Briefly describe the feature

- As a paralus user, I would like to set an auto-generated password during installation thus avoid admin to reset the password after installation
- As an admin, when I first login I would like to reset by password before logging in.
- Applicable while creating new users via dashboard, cli

### What problem does this feature solve? Please link any relevant documentation or Issues

- Improves paralus usage for new users

**Comment by akshay196** [comment]
Tasks to complete this feature:
1. Update Kratos library SDK in Paralus core (New Kratos library supports accepting password in account creation) [@akshay196 ]
2. Auto generate password in Paralus init script [@rustiever ]
3. Helm chart changes
4. Dashboard changes (Detect "admin" use is login for first time and ask to set password)

**Comment by akshay196** [comment]
New PRs:
- https://github.com/paralus/paralus/pull/124
- https://github.com/paralus/dashboard/pull/152
- https://github.com/paralus/helm-charts/pull/70

**Comment by niravparikh05** [comment]
This is completed and merged. Available with Paralus helm version v0.2.1
