### ISSUE TITLE
Make swagger available for the user facing apis

### ISSUE THREAD

**Issue by nirav-rafay** [paralus/paralus#97]
### Briefly describe the feature

- Make swagger ui available for below
Partner
Organization
Project
User
Group
Role
Role Permission
Kubectl Setting
OIDC Provider
Audit Log

### What problem does this feature solve? Please link any relevant documentation or Issues

- Makes it easy for developers wanting to interface with core component

**Comment by niravparikh05** [comment]
swagger is now available at - https://paralus.github.io/paralus/

few pending items -
want to remove try out as this just serves as api documentation reference and is not backed by api server to fulfil the requests

**Comment by niravparikh05** [comment]
this will be taken care of by https://github.com/paralus/website/issues/54

Closing this issue.
